default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: <%= ENV['DB_HOST'] %>
  port: <%= ENV['DB_PORT'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>

development:
  <<: *default
  database: stonknotes_development

test:
  <<: *default
  database: stonknotes_test

production:
  <<: *default
  database: stonknotes_production
